export const ADD_ARTICLE = 'ADD_ARTICLE'
export const GET_ARTICLES_BY_ID = 'GET_ARTICLES_BY_ID'

export const GET_ARTICLES_REQUEST = 'GET_ARTICLES_REQUEST'
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS'
export const GET_ARTICLES_FAILURE = 'GET_ARTICLES_FAILURE'
